const PDFDocument = require('pdfkit');

// ── PDF ───────────────────────────────────────────────────────────────────────

const generateComplaintPDF = (complaints, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=municipal-complaints-${Date.now()}.pdf`);
  doc.pipe(res);

  doc.fontSize(22).font('Helvetica-Bold').text('EthioBridge Municipal Complaints', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#666').text(
    `${complaints.length} complaint(s) | Generated ${new Date().toLocaleDateString()}`,
    { align: 'center' }
  );
  doc.moveDown(1);

  complaints.forEach((c, i) => {
    if (i > 0) doc.addPage();
    doc.fillColor('#000');
    drawSection(doc, `Complaint #${i + 1}`, [
      ['Tracking ID', c.trackingId],
      ['Title', c.title],
      ['Issue Type', c.issueType],
      ['Department', c.category || c.department],
      ['Priority', c.priority],
      ['Status', c.status],
      ['Assigned Level', c.assignedLevel],
      ['Assigned Department', c.assignedToDepartment],
      ['Submitted On', c.createdAt ? new Date(c.createdAt).toLocaleString() : '—'],
    ]);

    drawSection(doc, 'Location', [
      ['Subcity', c.subcity],
      ['Woreda', c.woredaName],
      ['Location Text', c.locationText],
      ['GPS', c.latitude && c.longitude ? `${c.latitude}, ${c.longitude}` : '—'],
    ]);

    drawSection(doc, 'Reporter', [
      ['Name', c.reporterName],
      ['Phone', c.reporterPhone],
      ['Email', c.reporterEmail],
    ]);

    doc.moveDown(0.5);
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Description');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#555').text(c.description || 'No description provided', { lineGap: 4 });

    if (c.assessment && (c.assessment.publicSafetyRisk || c.assessment.requiresMajorInfrastructureReplacement ||
      c.assessment.requiresSubcityApproval || c.assessment.requiresBudgetAboveLimit ||
      c.assessment.requiresSpecialEquipment || c.assessment.affectsMoreThan50Households)) {
      doc.moveDown(0.5);
      drawSection(doc, 'Woreda Assessment', [
        ['Special Equipment', c.assessment.requiresSpecialEquipment ? 'Yes' : 'No'],
        ['Above Woreda Budget', c.assessment.requiresBudgetAboveLimit ? 'Yes' : 'No'],
        ['Subcity Approval Required', c.assessment.requiresSubcityApproval ? 'Yes' : 'No'],
        ['>50 Households Affected', c.assessment.affectsMoreThan50Households ? 'Yes' : 'No'],
        ['Public Safety Risk', c.assessment.publicSafetyRisk ? 'Yes' : 'No'],
        ['Major Infrastructure Replacement', c.assessment.requiresMajorInfrastructureReplacement ? 'Yes' : 'No'],
      ]);
    }

    if (c.responses && c.responses.length) {
      doc.moveDown(0.5);
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Response History');
      doc.moveDown(0.3);
      c.responses.forEach((r) => {
        doc.fontSize(9).font('Helvetica-Bold').fillColor('#444').text(
          `${r.officerName || 'Officer'} (${r.fromLevel}) - ${r.at ? new Date(r.at).toLocaleString() : ''}`
        );
        doc.fontSize(9).font('Helvetica').fillColor('#666').text(r.message || '');
        doc.moveDown(0.3);
      });
    }

    if (c.escalationHistory && c.escalationHistory.length) {
      doc.moveDown(0.5);
      drawSection(doc, 'Escalation History', c.escalationHistory.map((e) => [
        `${e.fromLevel || '—'} → ${e.toLevel || '—'}`,
        `${e.triggeredByName || 'System'} (${e.triggeredBy || ''}) - ${e.at ? new Date(e.at).toLocaleString() : ''}`,
      ]));
    }

    doc.moveDown(1);
  });

  doc.fontSize(8).font('Helvetica').fillColor('#999').text(
    'Generated by EthioBridge Municipal Complaint Management System.',
    { align: 'center' }
  );
  doc.end();
};

// ── Excel (SpreadsheetML) ─────────────────────────────────────────────────────

const generateComplaintExcel = (complaints) => {
  const header = `<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <Worksheet ss:Name="Municipal Complaints">
  <Table>
   <Row>
    <Cell><Data ss:Type="String">Tracking ID</Data></Cell>
    <Cell><Data ss:Type="String">Title</Data></Cell>
    <Cell><Data ss:Type="String">Issue Type</Data></Cell>
    <Cell><Data ss:Type="String">Department</Data></Cell>
    <Cell><Data ss:Type="String">Priority</Data></Cell>
    <Cell><Data ss:Type="String">Status</Data></Cell>
    <Cell><Data ss:Type="String">Assigned Level</Data></Cell>
    <Cell><Data ss:Type="String">Assigned Department</Data></Cell>
    <Cell><Data ss:Type="String">Subcity</Data></Cell>
    <Cell><Data ss:Type="String">Woreda</Data></Cell>
    <Cell><Data ss:Type="String">Reporter</Data></Cell>
    <Cell><Data ss:Type="String">Submitted On</Data></Cell>
    <Cell><Data ss:Type="String">Forwarded On</Data></Cell>
    <Cell><Data ss:Type="String">Escalated On</Data></Cell>
    <Cell><Data ss:Type="String">Resolved On</Data></Cell>
   </Row>`;

  const rows = complaints.map(c => `
   <Row>
    <Cell><Data ss:Type="String">${escapeXml(c.trackingId || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.title || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.issueType || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.category || c.department || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.priority || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.status || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.assignedLevel || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.assignedToDepartment || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.subcity || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.woredaName || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.reporterName || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${c.createdAt ? new Date(c.createdAt).toLocaleDateString() : ''}</Data></Cell>
    <Cell><Data ss:Type="String">${c.forwardedAt ? new Date(c.forwardedAt).toLocaleDateString() : ''}</Data></Cell>
    <Cell><Data ss:Type="String">${c.escalatedAt ? new Date(c.escalatedAt).toLocaleDateString() : ''}</Data></Cell>
    <Cell><Data ss:Type="String">${c.resolvedAt ? new Date(c.resolvedAt).toLocaleDateString() : ''}</Data></Cell>
   </Row>`).join('');

  const footer = `
  </Table>
 </Worksheet>
</Workbook>`;

  return header + rows + footer;
};

function drawSection(doc, title, rows) {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text(title);
  doc.moveDown(0.3);
  rows.forEach(([label, value]) => {
    if (!value || value === '—' || value === 'undefined') return;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#555').text(`${label}: `, { continued: true });
    doc.fontSize(9).font('Helvetica').fillColor('#333').text(String(value));
  });
  doc.moveDown(0.5);
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

module.exports = { generateComplaintPDF, generateComplaintExcel };
