const PDFDocument = require('pdfkit');

// ── Acknowledgment PDF (single complaint) ─────────────────────────────────────

const generateAcknowledgmentPDF = (complaint, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=governance-acknowledgment-${complaint.trackingId}.pdf`);
  doc.pipe(res);

  doc.fontSize(22).font('Helvetica-Bold').text('EthioBridge Service Governance Complaint', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(12).font('Helvetica').fillColor('#444').text('Acknowledgement Receipt', { align: 'center' });
  doc.moveDown(1);

  drawSection(doc, 'Tracking Details', [
    ['Tracking ID', complaint.trackingId],
    ['Status', complaint.status],
    ['Submitted On', complaint.createdAt ? new Date(complaint.createdAt).toLocaleString() : '—'],
  ]);

  drawSection(doc, 'Complaint', [
    ['Category', complaint.category],
    ['Office / Bureau', complaint.office],
    ['Subcity', complaint.subcity],
    ['Woreda', complaint.woredaName],
    ['Incident Date', complaint.incidentDate ? new Date(complaint.incidentDate).toLocaleDateString() : '—'],
    ['Incident Time', complaint.incidentTime || '—'],
  ]);

  drawSection(doc, 'Reporter', complaint.isAnonymous ? [
    ['Name', 'Anonymous'],
    ['Phone', complaint.reporterPhone],
  ] : [
    ['Name', complaint.reporterName],
    ['Phone', complaint.reporterPhone],
    ['Email', complaint.reporterEmail],
  ]);

  doc.moveDown(0.5);
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Description');
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#555').text(complaint.description || 'No description provided', { lineGap: 4 });

  doc.moveDown(1.5);
  doc.fontSize(10).font('Helvetica').fillColor('#666').text(
    `Your complaint has been submitted to the Subcity Governance Office of ${complaint.subcity || 'your subcity'}.`,
    { align: 'center' }
  );
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#666').text(
    `Keep your Tracking ID safe — you can check progress at any time using ${complaint.trackingId} and your phone number.`,
    { align: 'center' }
  );

  doc.moveDown(1);
  doc.fontSize(8).font('Helvetica').fillColor('#999').text(
    'Generated by EthioBridge Service Governance System.',
    { align: 'center' }
  );
  doc.end();
};

// ── Bulk export (PDF) ─────────────────────────────────────────────────────────

const generateGovernancePDF = (complaints, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=governance-complaints-${Date.now()}.pdf`);
  doc.pipe(res);

  doc.fontSize(22).font('Helvetica-Bold').text('EthioBridge Governance Complaints', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#666').text(
    `${complaints.length} complaint(s) | Generated ${new Date().toLocaleDateString()}`,
    { align: 'center' }
  );
  doc.moveDown(1);

  complaints.forEach((c, i) => {
    if (i > 0) doc.addPage();
    doc.fillColor('#000');
    drawSection(doc, `Complaint #${i + 1}`, [
      ['Tracking ID', c.trackingId],
      ['Category', c.category],
      ['Office / Bureau', c.office],
      ['Status', c.status],
      ['Subcity', c.subcity],
      ['Woreda', c.woredaName],
      ['Submitted On', c.createdAt ? new Date(c.createdAt).toLocaleString() : '—'],
      ['Resolved On', c.resolvedAt ? new Date(c.resolvedAt).toLocaleString() : '—'],
    ]);

    drawSection(doc, 'Reporter', c.isAnonymous ? [
      ['Name', 'Anonymous'],
      ['Phone', c.reporterPhone],
    ] : [
      ['Name', c.reporterName],
      ['Phone', c.reporterPhone],
      ['Email', c.reporterEmail],
    ]);

    if (c.adminActions && c.adminActions.length) {
      drawSection(doc, 'Administrative Actions', c.adminActions.map((a) => [
        a.action,
        `${a.recordedByName || ''} - ${a.recordedAt ? new Date(a.recordedAt).toLocaleString() : ''}`,
      ]));
    }

    doc.moveDown(0.5);
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Description');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#555').text(c.description || 'No description provided', { lineGap: 4 });

    if (c.resolutionNote) {
      doc.moveDown(0.5);
      drawSection(doc, 'Resolution Note', [['Note', c.resolutionNote]]);
    }

    doc.moveDown(1);
  });

  doc.fontSize(8).font('Helvetica').fillColor('#999').text(
    'Generated by EthioBridge Service Governance System.',
    { align: 'center' }
  );
  doc.end();
};

// ── Bulk export (Excel / SpreadsheetML) ───────────────────────────────────────

const generateGovernanceExcel = (complaints) => {
  const header = `<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <Worksheet ss:Name="Governance Complaints">
  <Table>
   <Row>
    <Cell><Data ss:Type="String">Tracking ID</Data></Cell>
    <Cell><Data ss:Type="String">Category</Data></Cell>
    <Cell><Data ss:Type="String">Office / Bureau</Data></Cell>
    <Cell><Data ss:Type="String">Status</Data></Cell>
    <Cell><Data ss:Type="String">Subcity</Data></Cell>
    <Cell><Data ss:Type="String">Woreda</Data></Cell>
    <Cell><Data ss:Type="String">Reporter</Data></Cell>
    <Cell><Data ss:Type="String">Submitted On</Data></Cell>
    <Cell><Data ss:Type="String">Resolved On</Data></Cell>
    <Cell><Data ss:Type="String">Escalated On</Data></Cell>
    <Cell><Data ss:Type="String">Admin Action</Data></Cell>
   </Row>`;

  const rows = complaints.map((c) => `
   <Row>
    <Cell><Data ss:Type="String">${escapeXml(c.trackingId || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.category || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.office || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.status || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.subcity || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.woredaName || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml(c.isAnonymous ? 'Anonymous' : c.reporterName || '')}</Data></Cell>
    <Cell><Data ss:Type="String">${c.createdAt ? new Date(c.createdAt).toLocaleDateString() : ''}</Data></Cell>
    <Cell><Data ss:Type="String">${c.resolvedAt ? new Date(c.resolvedAt).toLocaleDateString() : ''}</Data></Cell>
    <Cell><Data ss:Type="String">${c.escalatedAt ? new Date(c.escalatedAt).toLocaleDateString() : ''}</Data></Cell>
    <Cell><Data ss:Type="String">${escapeXml((c.adminActions || []).map((a) => a.action).join(', '))}</Data></Cell>
   </Row>`).join('');

  const footer = `
  </Table>
 </Worksheet>
</Workbook>`;

  return header + rows + footer;
};

function drawSection(doc, title, rows) {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text(title);
  doc.moveDown(0.3);
  rows.forEach(([label, value]) => {
    if (!value || value === '—' || value === 'undefined') return;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#555').text(`${label}: `, { continued: true });
    doc.fontSize(9).font('Helvetica').fillColor('#333').text(String(value));
  });
  doc.moveDown(0.5);
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

module.exports = { generateAcknowledgmentPDF, generateGovernancePDF, generateGovernanceExcel };
