const PDFDocument = require('pdfkit');

const generateReportPDF = (report, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=report-${report.reportId || Date.now()}.pdf`);
  doc.pipe(res);

  doc.fontSize(22).font('Helvetica-Bold').text('EthioBridge Infrastructure Report', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#666').text(`Generated on ${new Date().toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(1);

  doc.fillColor('#000');
  drawSection(doc, 'Report Information', [
    ['Report ID', report.reportId],
    ['Title', report.title],
    ['Category', report.category],
    ['Severity', report.severityLevel],
    ['Status', report.status],
    ['Date Reported', report.createdAt ? new Date(report.createdAt).toLocaleDateString() : '—'],
    ['Incident Date', report.incidentDate ? new Date(report.incidentDate).toLocaleDateString() : '—'],
  ]);

  drawSection(doc, 'Location', [
    ['Region', report.region],
    ['Zone', report.zone],
    ['Woreda', report.woreda],
    ['Kebele', report.kebele],
    ['City', report.city],
    ['Address', report.address],
    ['Specific Location', report.specificLocation],
    ['GPS', report.latitude && report.longitude ? `${report.latitude}, ${report.longitude}` : '—'],
  ]);

  drawSection(doc, 'Assignment', [
    ['Responsible Organization', report.autoAssignedOrganization],
    ['Assigned Department', report.assignedDepartment],
    ['Assigned To', report.assignedTo?.fullName || '—'],
    ['Due Date', report.dueDate ? new Date(report.dueDate).toLocaleDateString() : '—'],
    ['Completed At', report.completedAt ? new Date(report.completedAt).toLocaleDateString() : '—'],
  ]);

  doc.moveDown(0.5);
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Description');
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#555').text(report.description || 'No description provided', { lineGap: 4 });
  doc.moveDown(1);

  if (report.timeline && report.timeline.length > 0) {
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text('Timeline History');
    doc.moveDown(0.3);
    const sorted = [...report.timeline].reverse();
    sorted.forEach((event, i) => {
      const date = event.createdAt ? new Date(event.createdAt).toLocaleString() : '';
      doc.fontSize(9).font('Helvetica-Bold').fillColor('#444').text(`${event.action.toUpperCase()} - ${date}`);
      doc.fontSize(9).font('Helvetica').fillColor('#666').text(event.description || '');
      if (event.note) doc.fontSize(8).fillColor('#888').text(`Note: ${event.note}`);
      if (event.performedByName) doc.fontSize(8).fillColor('#888').text(`By: ${event.performedByName} (${event.performedByRole})`);
      doc.moveDown(0.3);
    });
  }

  if (report.rating) {
    doc.moveDown(0.5);
    drawSection(doc, 'Citizen Feedback', [
      ['Rating', `${'★'.repeat(report.rating)}${'☆'.repeat(5 - report.rating)} (${report.rating}/5)`],
      ['Feedback', report.feedback || '—'],
    ]);
  }

  if (report.rejectionReason) {
    doc.moveDown(0.5);
    drawSection(doc, 'Rejection Details', [
      ['Reason', report.rejectionReason],
    ]);
  }

  doc.moveDown(1);
  doc.fontSize(8).font('Helvetica').fillColor('#999').text('This report was generated by EthioBridge Infrastructure Reporting System.', { align: 'center' });

  doc.end();
};

const generateBulkPDF = (reports, res) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=reports-bulk-${Date.now()}.pdf`);
  doc.pipe(res);

  doc.fontSize(20).font('Helvetica-Bold').text('EthioBridge - Infrastructure Reports Summary', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('#666').text(`${reports.length} reports | Generated ${new Date().toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(1);

  reports.forEach((r, i) => {
    if (i > 0 && i % 20 === 0) doc.addPage();

    doc.fontSize(11).font('Helvetica-Bold').fillColor('#333').text(`${i + 1}. ${r.reportId || 'N/A'} - ${r.title}`);
    doc.fontSize(9).font('Helvetica').fillColor('#666');
    doc.text(`Category: ${r.category} | Severity: ${r.severityLevel} | Status: ${r.status}`);
    doc.text(`Region: ${r.region} | Reported: ${r.createdAt ? new Date(r.createdAt).toLocaleDateString() : '—'}`);
    if (r.autoAssignedOrganization) doc.text(`Organization: ${r.autoAssignedOrganization}`);
    doc.moveDown(0.5);
  });

  doc.end();
};

function drawSection(doc, title, rows) {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#333').text(title);
  doc.moveDown(0.3);
  rows.forEach(([label, value]) => {
    if (!value || value === '—' || value === 'undefined') return;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#555').text(`${label}: `, { continued: true });
    doc.fontSize(9).font('Helvetica').fillColor('#333').text(String(value));
  });
  doc.moveDown(0.5);
}

module.exports = { generateReportPDF, generateBulkPDF };
